openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0
paths:
  /api/users:
    get:
      summary: Obtiene todos los usuarios de la super base
      tags:
        - Users
      responses:
        "200":
          description: Los usuarios fueron obtenidos OK desde la DB
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Graba un usuario
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/createUser'
      responses:
        "201":
          description: Usuario creado
        "400":
          description: Faltan datos

  /api/users/{uid}:
    get:
      summary: Obtiene un usuario de la base de datos por id
      tags:
        - Users
      parameters:
        - name: uid
          in: path
          required: true
          description: id del usuario que se está solicitando
          schema:
            type: string
      responses:
        "200":
          description: Recupera un usuario de la DB, según el uid que enviamos en la ruta como parámetro

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: Id autogenerado de mongo
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido
        email:
          type: string
          description: Correo electrónico
        password:
          type: string
          description: Contraseña de acceso
      example:
        _id: "Iv1.1db47e8230110a7a"
        first_name: Tiago
        last_name: Isola
        email: dtiagoandresisola@hotmail.com
        password: 123

  requestBodies:
    createUser:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      description: Datos para crear un nuevo usuario
